### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by ghoshbishakh** [NITDgpOS/SecureSnaps#12]

**Comment by HarshKhatore** [comment]
We can use [pigar](https://github.com/damnever/pigar), which dynamically creates custom requirements.txt, which the user can run and then we can use the requirements.txt to install modules?

**Comment by Aniq55** [comment]
@HarshKhatore shall I assign this issue to you?

**Comment by HarshKhatore** [comment]
@Aniq55  Yes sure, but I would like to discuss this, as for how to use pigar, should I write a bash script that checks for pigar's installation in the system, runs it and then creates requirements.txt or what else would be appropriate?

**Comment by Aniq55** [comment]
I think it's better not complicating things at this stage and add the entries in the `requirements.txt` manually @HarshKhatore 
We already have a `requirements.txt` file, the issue requires involving more dependencies as the project develops.
