### ISSUE TITLE
New algorithm for extracting key tuples from password

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#18]
Implement a new algorithm for generating key tuples from the password and compare against the existing algorithm.

**Comment by mayukhbh** [comment]
I want to work on this.

**Comment by Aniq55** [comment]
Assigned to @mayukhbh  @amitsharma1919 @96sudeshnasen

**Comment by amitsharma1919** [comment]
I want to work on this. I'll design a new algorithm
