### ISSUE TITLE
Create an Online platform for SecureSnaps

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#22]
* Create a website where people can upload their image and enter a password and then choose to Encrypt or Decrypt. 
* Then return the requisite image (encrypted/decrypted) to the user and flush the original image from the database.

Design similar to #41

**Comment by HarshKhatore** [comment]
@Aniq55  Will the website be hosted independently or use GitHub Pages?

**Comment by Aniq55** [comment]
I don't think the upload feature will work on Github pages. @djmgit any comments?

**Comment by djmgit** [comment]
nopes, gh-pages can only host static websites, you require some deployment platform for running python and a suitable framework (django or flask)

**Comment by djmgit** [comment]
Thats not a problem, we can use heroku for testing dev builds

**Comment by djmgit** [comment]
@Aniq55 
We can use SecureSnaps as a library and use a python framework to create an online platform and deploy it on heroku. Then we can use travis CI for continuous testing and deployment on each push to github.

**Comment by parulc7** [comment]
I would like to work on this issue. Would it be a problem if  a MEAN Based Website is used for this?

**Comment by Aniq55** [comment]
@djmgit could you please reply @Deathrow77 ?

**Comment by djmgit** [comment]
@Deathrow77 securesnaps is in python,  you need to use it as a library in your web app.  If you use mean, your back end will be in nodejs.  How will you link python code?  Will you use system calls or some kind of binding?

**Comment by Aniq55** [comment]
@arulthileeban has already started working on it using `flask`. Discuss with him, the possibility of collaborating on this issue. @Deathrow77

**Comment by parulc7** [comment]
It can be done using jquery ajax module.
See this for reference -- [https://stackoverflow.com/questions/32288722/call-python-function-from-js](url)

**Comment by Aniq55** [comment]
@Deathrow77 the basic structure is merged, you may now contribute to the web app.

**Comment by Aniq55** [comment]
@arulthileeban please send a screenshot of the webapp.
