### ISSUE TITLE
Terminal command ssnaps not working

### ISSUE THREAD

**Issue by HarshKhatore** [NITDgpOS/SecureSnaps#30]
Description
-----------
The absolute path should be given for decoder.py and encoder.py when SecureSnaps is used through the terminal at any location on the system other than SecureSnaps directory.

Example:
SecureSnaps -e <path_to_image_file> 
(Ran with present working directory as Desktop)

Results
-------
python3: can't open file 'encoder.py' : [Errno 2] No such file or directory

**Comment by HarshKhatore** [comment]
We can use the location for encoder.py and decoder.py when we set up the terminal command for SecureSnaps i.e.
from ` ln -s "$HOME"/<path>/SecureSnaps` we can append `ln -s "$HOME"/<path>/ ` to both encoder.py and decoder.py for always correct execution.

**Comment by Aniq55** [comment]
@HarshKhatore leave this for now. Work on this when the coding period starts.

**Comment by HarshKhatore** [comment]
@Aniq55 Okay.

**Comment by HarshKhatore** [comment]
How should we store the value to the path to encoder.py & decoder.py?
We can use a separate text file to store the path once or we can use export command in the shell? We also need to make arrangements if the user changes the location of SecureSnaps directory.

**Comment by Aniq55** [comment]
@HarshKhatore these things will be taken care of in the setup script #32

**Comment by Aniq55** [comment]
I've added a new way to install `ssnaps` command.
