### ISSUE TITLE
Create setup script

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#32]
Currently, registering SecureSnaps as a terminal command involves the user executing certain commands, create a bash file called `setup` which first takes care of installing the dependencies and then registering `ssnaps` as a valid terminal command.

example, this code plus what is specified.
```
 chmod +x ssnaps
 ln -s "$HOME"/<path>/SecureSnaps /usr/local/bin
```
Work with #30

**Comment by HarshKhatore** [comment]
@Aniq55 This can be worked after the coding period starts, in parallel with [#30](https://github.com/NITDgpOS/SecureSnaps/issues/30)?
Or should this be done now?

**Comment by Aniq55** [comment]
@HarshKhatore yes, in parallel with #30 but after the coding period begins.
