### ISSUE TITLE
Create a GUI for testing SecureSnaps

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#35]
Create a GUI for SecureSnaps, where the user can select the image on his disk and then enter a password and then choose Encrypt or Decrypt.
* Divide the entire frame into two parts: `Input Image` and `Output Image`
* Discuss the UI before solving this issue.
* This issue makes the testing procedure simpler

**Comment by Aniq55** [comment]
![ssnaps_gui_mockup](https://user-images.githubusercontent.com/20151858/33558601-46143c62-d930-11e7-9697-c94ab5ec133b.png)

**Comment by Ankush1529** [comment]
I would like to contribute to this.

**Comment by Aniq55** [comment]
Assigned to @Ankush1529
