### ISSUE TITLE
Create a GUI for deploying SecureSnaps

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#41]
The GUI will have features to
* add images (in batch) or one by one
* Specify the output folder
* Option to flush the original images

**Comment by Aniq55** [comment]
![ssnaps_gui_mockup_deploy](https://user-images.githubusercontent.com/20151858/33559783-ebae18ca-d933-11e7-935d-c35294e24d9a.png)

**Comment by aditodkar** [comment]
I would like to work on this issue.

**Comment by Aniq55** [comment]
Assigned to @aditodkar @eulerkochy

**Comment by eulerkochy** [comment]
I would like to contribute to the project by working on this issue

**Comment by parulc7** [comment]
Is there any chance that I can contribute too? BTW. . . which GUI Module are you willing to use?

**Comment by Aniq55** [comment]
@Deathrow77 after the basic structure is ready, there will be issues for enhancement then you can contribute.

**Comment by Aniq55** [comment]
@aditodkar @Deathrow77 @eulerkochy  you may contribute to this, but kindly use `PAGE` othersiwe your PR wont be accepted.

**Comment by Aniq55** [comment]
@eulerkochy your files have been removed. Your effort is respected but the design wasn't up to the mark. The colors shown in the mockup is only for explaining.
