### ISSUE TITLE
Saturation levels of original and decoded image not same

### ISSUE THREAD

**Issue by Aniq55** [NITDgpOS/SecureSnaps#9]
The quality of the image degrades on saving it.
There is some loss of saturation while encoding and while decoding the same happens, making the original and decoded pictures look different even though the form and pattern is recovered 100%

P.S. Happens only with `.jpg` images, `.png` images work fine

**Comment by ghoshbishakh** [comment]
how is this possible?

**Comment by Aniq55** [comment]
I dont know, .PNG images work fine, but .JPEG has problem. @ghoshbishakh
